language: go

go:
  - 1.x

install:
  - go get -t -v ./...

before_deploy:
  - . $HOME/.nvm/nvm.sh
  - nvm install 10 && nvm use 10
  - npm install netlify-cli -g

deploy:
  provider: script
  script: netlify deploy --dir=tmpl --prod
  on:
    branch: master
