language: go

go:
  - 1.x

sudo: false

install:
  - go get -t -v ./...

before_deploy:
  - . $HOME/.nvm/nvm.sh
  - nvm install latest
  - nvm use latest
  - npm install netlify-cli -g

deploy:
  provider: script
  script: netlify deploy --dir=tmpl --prod
  skip_cleanup: true
  on:
    branch: master
