language: go

go:
  - 1.x

sudo: false

install:
  - go get -t -v ./...
  - npm install netlify-cli -g

deploy:
  provider: script
  script: netlify deploy --dir=tmpl --prod
  skip_cleanup: true
  on:
    branch: master
