version: "2"

services:
  caddy:
    image: abiosoft/caddy
    volumes:
      - ./tmpl:/srv
    ports:
      - 80:2015
  webhook:
    build: ./
    volumes:
      - ./:/srv
    ports:
      - 9000:9000