name: PR auto close, if you stay more than 8 days open

on:
  workflow_dispatch:
  schedule:
  - cron: '*/15 * * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: >
          This PR has been automatically marked as closed because it has not had
          recent activity. They will wait 15 days for your interaction, after
          that the PR will be closed.
          Please read more in https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md
        stale-pr-label: 'stale'
        days-before-stale: 15
        days-before-close: 7
