name: tests

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    name: Running test
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
    - uses: actions/checkout@1.0.0
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Run tests
      run: go test
